    # netlify.toml
    [functions]
    external_node_modules = ["express"] # Specify external modules if needed
    node_bundler = "esbuild" # Or "zip"

    [[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat" # Redirect to your function
    status = 200
    force = true